name: Run hello.py using GitHub Actions

on:
  push:
    branches:
      - master

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run hello.py
      run: python hello.py
